# Generated by Django 5.2.12 on 2026-09-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scripture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradition', models.CharField(choices=[('gita', 'Bhagavad Gita'), ('quran', 'Quran'), ('bible', 'Bible')], max_length=20)),
                ('book', models.CharField(blank=True, max_length=100)),
                ('chapter', models.IntegerField()),
                ('verse', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
